"""
.. _flashH

FlashH
------

This module provides variables that are drawn from your simulation's ``Flash.h`` header file ``#defines`` statements.
"""
CONSTANT_ZERO= 0
CONSTANT_ONE = 1
CONSTANT_TWO = 2

NDIM = 1

PROP_VARS_BEGIN =  CONSTANT_ZERO
UNK_VARS_BEGIN  = PROP_VARS_BEGIN

ABSR_VAR = 0
COND_VAR = 1
DBGS_VAR = 2
DENS_VAR = 3
DEPO_VAR = 4
DFCF_VAR = 5
EELE_VAR = 6
EINT_VAR = 7
EION_VAR = 8
EMIS_VAR = 9
ENER_VAR = 10
ERAD_VAR = 11
FLLM_VAR = 12
GAMC_VAR = 13
GAME_VAR = 14
LASE_VAR = 15
MGDC_VAR = 16
PELE_VAR = 17
PION_VAR = 18
PIPE_VAR = 19
PRAD_VAR = 20
PRES_VAR = 21
SHOK_VAR = 22
TELE_VAR = 23
TEMP_VAR = 24
TION_VAR = 25
TITE_VAR = 26
TRAD_VAR = 27
VELX_VAR = 28
VELY_VAR = 29
VELZ_VAR = 30
VOLX_VAR = 31
VOLY_VAR = 32
VOLZ_VAR = 33

NPROP_VARS = 34
PROP_VARS_END = PROP_VARS_BEGIN + NPROP_VARS - CONSTANT_ZERO

SPECIES_BEGIN = PROP_VARS_END + CONSTANT_ZERO
CHAM_SPEC = 34
TARG_SPEC = 35


NSPECIES = 2
SPECIES_END = SPECIES_BEGIN + NSPECIES - CONSTANT_ZERO

MASS_SCALARS_BEGIN = SPECIES_END + CONSTANT_ZERO

NONREP_MGDR_DCCE714B_000001_MSCALAR = 36
NONREP_MGDR_DCCE714B_000002_MSCALAR = 37
NONREP_MGDR_DCCE714B_000003_MSCALAR = 38
NONREP_MGDR_DCCE714B_000004_MSCALAR = 39
NONREP_MGDR_DCCE714B_000005_MSCALAR = 40
NONREP_MGDR_DCCE714B_000006_MSCALAR = 41
SUMY_MSCALAR = 42
YE_MSCALAR = 43

NMASS_SCALARS = 8
MASS_SCALARS_END = MASS_SCALARS_BEGIN+NMASS_SCALARS-CONSTANT_ZERO

NMASS_SCALAR_GROUPS = 0 

NMULTIFLUID = 0
MULTIFLUID_BEGIN = MASS_SCALARS_END+CONSTANT_ZERO
MFA_BEGIN = MULTIFLUID_BEGIN
MFA_END = MFA_BEGIN+NMULTIFLUID-CONSTANT_ZERO
MFB_BEGIN = MFA_BEGIN+NMULTIFLUID
MFB_END = MFB_BEGIN+NMULTIFLUID-CONSTANT_ZERO
MULTIFLUID_END = MFB_END









NUNK_VARS = NPROP_VARS + NSPECIES + NMASS_SCALARS + 2*NMULTIFLUID
UNK_VARS_END = UNK_VARS_BEGIN - CONSTANT_ZERO + NUNK_VARS



    
NFACE_VARS =  0

GRID_WITH_MONOTONIC = 1
GRID_GC_LAYERS_ALWAYS_EVEN = 1
PM_OPTIMIZE_MORTONBND_FETCHLIST = 1
FLASH_GRID_PARAMESH4DEV_SURR_BLKS_OPTION = 1
HYPRE_UNIFIED = 1
NUMSYS = 3
IMAGZ = 1
IMAG = 2
IVISCOSITY = 3
FLASH_IO_EXPERIMENTAL = 1
FLASH_MULTISPECIES = 1
MS_MAXELEMS = 6
SPECIES_SETUPVAR = 1
FLASH_EOS_MULTITYPE = 1
FLASH_UHD_HYDRO = 1
FLASH_UHD_3T = 1
MGD_MAXGROUPS = 101
FLASH_GRID_PARAMESH4DEV = 1
FLASH_GRID_PARAMESH3OR4 = 1
IO_HDF5_PARALLEL = 1
FLASH_USE_MEMORYUSAGE = 1
FLASH_HYDRO_UNSPLIT = 1
FLASH_EDEP = 1
ED_MAXPULSES = 5
ED_MAXPULSESECTIONS = 64
ED_MAXBEAMS = 6
FLASH_GRID_PARAMESH = 1
GR_LREFMAXTIMES = 20
FLASH_GRID_PARTICLES = 1
FLASH_IO_HDF5 = 1
FLASH_EOS = 1
FLASH_IO = 1
